WIDTH, HEIGHT = 800, 675
SCREEN_SIZE = WIDTH, HEIGHT

CARD_WIDTH = 128
CARD_SCALE = CARD_WIDTH, CARD_WIDTH
CARD_VERTICAL_OFFSET = 28

STOCK_INDEX = 0
WASTE_INDEX = 1
TABLEAU_START_INDEX = 2
FOUNDATION_START_INDEX = 9
